### PR TITLE
Add store

### PR DESCRIPTION
**Pull request by MarioRodrigues10**

### CODE REVIEW

**Comment by feliciofilipe** [comment]
This should only be discussed, and if the case implemented after version 2.0.0 launched

**Comment by MarioRodrigues10** [comment]
I will convert this PR to draft and keep it as much updated as possible with Store repository and Atomic Repository in order to be implemented in the future.

**Comment by feliciofilipe** [comment]
Close this plz

**Comment by MarioRodrigues10** [comment]
@feliciofilipe why?
This PR has the purpose to be merged at 2.0 version and will be in draft until there.

**Comment by diogogmatos** [comment]
[Add Store](https://trello.com/c/rshhHIyq/4-add-store)

**Comment by joaodiaslobo** [comment]
This PR will be closed since this is a feature that's only going to be worked on after the `1.0` release, the work of keeping this branch up to date is highly unnecessary and time consuming.

**Pull request closed without merging**
