### PR TITLE
feat: button and spinner components

### PR DESCRIPTION
**Pull request by joaodiaslobo**
Very complete button component with colors, icons, sizes, variants, loading state, etc. 
Also adds a loading spinner component.

image
image
image
image

### CODE REVIEW

**Review by MarioRodrigues10 — CHANGES_REQUESTED** [review]
Just like in this storybook [example](https://phoenix-storybook-demo.fly.dev/storybook/components/badge?theme=default), it would be nice to show the differences between the different buttons.

Here's how our buttons currently look:
image

**Comment by joaodiaslobo** [comment]
> Just like in this storybook [example](https://phoenix-storybook-demo.fly.dev/storybook/components/badge?theme=default), it would be nice to show the differences between the different buttons.
> 
> Here's how our buttons currently look: (image)

@MarioRodrigues10 
It seems like the CSS classes aren't loading properly on your side! Probably because you haven't updated your Tailwind CSS version. Please run `mix tailwind.install`

**Comment by MarioRodrigues10** [comment]
@joaodiaslobo , could you add that command to `mix setup` ?

**Review by MarioRodrigues10 — APPROVED** [review]
What an awesome job :star_struck:

**Pull request merged**
