### PR TITLE
refactor: improve 404 page design

### LINKED ISSUE #347: Improve 404 page design
To something like this:
image
A "Go back" button is in fault, by the way.

### PR DESCRIPTION
**Pull request by anubhav1206**
image

### CODE REVIEW

**Review by ruilopesm — CHANGES_REQUESTED** [review]
Thanks for your contribution, once again. A few points you may fix/improve:
- You should stick with the 404.html.heex file. Learn more [here](https://hexdocs.pm/phoenix_live_view/assigns-eex.html).
- I like the design, but it doesn't fit well with the rest of the application. Check the image I left at the issue and follow it, please.
- We are a Tailwind-first team. So that, you should always use Tailwind as your first tool and whenever you can't do something in Tailwind, start using CSS (spoiler: that rarely happens).

Any doubt, I'm here at your disposal 💪🏼

**Comment by anubhav1206** [comment]
> Thanks for your contribution, once again. A few points you may fix/improve:
> 
> * You should stick with the 404.html.heex file. Learn more [here](https://hexdocs.pm/phoenix_live_view/assigns-eex.html).
> * I like the design, but it doesn't fit well with the rest of the application. Check the image I left at the issue and follow it, please.
> * We are a Tailwind-first team. So that, you should always use Tailwind as your first tool and whenever you can't do something in Tailwind, start using CSS (spoiler: that rarely happens).
> 
> Any doubt, I'm here at your disposal 💪🏼

I'll look into it, thanks!

**Comment by anubhav1206** [comment]
Why is it that I cannot see a tailwind config file

**Comment by ruilopesm** [comment]
@anubhav1206 Tailwind config is inside the assets folder. Anyway, why do you need it?

**Comment by diogogmatos** [comment]
[refactor: improve 404 page design](https://trello.com/c/f4eu3okI/19-refactor-improve-404-page-design)

**Comment by MarioRodrigues10** [comment]
Unfortunately this doesn't fit with our design, and we want to move forward and get this page done, since there's no contributions since 24th August, 2023, I'm closing this so we can allocate one of our collaborators to work on this feature.

**Pull request closed without merging**
