### PR TITLE
refactor: improve coexistence between logged in and logged out users

### PR DESCRIPTION
**Pull request by ruilopesm**

### CODE REVIEW

**Review by MarioRodrigues10 — DISMISSED** [review]
Good job :+1:

**Comment by MarioRodrigues10** [comment]
Do it config.ex which handles which pages are in the sidebar should appear in here , or do you think that should be handled by who solves #311 ?

**Comment by ruilopesm** [comment]
@MarioRodrigues10 I think #311 must be solved first, then.

**Comment by ruilopesm** [comment]
Will be solved via #392.

**Pull request closed without merging**
