### PR TITLE
fix: show organization page

### PR DESCRIPTION
**Pull request by ruilopesm**

### CODE REVIEW

**Comment by MarioRodrigues10** [comment]
I think it would loook nicer if organization name and follow button are centered, what you think? :thinking: 

image
image

**Comment by ruilopesm** [comment]
@MarioRodrigues10 Agreed. I will implement it 💪🏼

**Comment by ruilopesm** [comment]
@MarioRodrigues10 Can you check it out? 👀

**Review by MarioRodrigues10 — APPROVED** [review]
:rocket:

**Pull request merged**
