### PR TITLE
Adds news link to navbar

### PR DESCRIPTION
**Pull request by 9thScientist**
This PR just adds a link to `cesium.di.uminho.pt/noticias` to the navbar.

### CODE REVIEW

**Comment by marcelo140** [comment]
All the routes are in english so I think it would be a better idea to ask jmv to change `/noticias` to `/news` and disable the atomic `/news` route that is not fully developed yet (*I think*). This way it would still be the same route once we move the news to atomic.

By the way, the `http://cesium.di.uminho.pt/news` is more developed than I expected. Do you have any idea what needs to be done in order to be usable @martinhoaragao ?

**Comment by martinhoaragao** [comment]
Absolutely agree with @marcelo140 .
Regarding the status of /news we should meet up to discuss it.

**Comment by martinhoaragao** [comment]
What's delaying this?

**Comment by 9thScientist** [comment]
@marcelo140 @martinhoaragao Is this PR ready to me merged?

**Comment by marcelo140** [comment]
As I've already told you I don't know if the `link_to` works and since you didn't test it I can't give you my approval.

**Comment by marcelo140** [comment]
Woops, my bad.

**Pull request merged**
