### PR TITLE
fix: seeds

### PR DESCRIPTION
**Pull request by ruilopesm**

### CODE REVIEW

**Review by MarioRodrigues10 — CHANGES_REQUESTED** [review]
When seeding accounts, admins were created with role student.
Also please seed with a random value of minimum and max entries on Session seeds

**Comment by MarioRodrigues10** [comment]
Related to the second point, make sure it passes the constraint on #315 please :pray:

**Comment by ruilopesm** [comment]
@MarioRodrigues10 Your first comment was fixed on #317.

**Comment by MarioRodrigues10** [comment]
Alright, #317 is approved , make sure to update this branch and do what i asked in the 2nd comment :pray:

**Review by MarioRodrigues10 — APPROVED** [review]
Good Job :rocket:

**Pull request merged**
